import{useMemo,useState}from'react';import{Home,NotebookPen,Calculator,FileText,Palette,Settings,Share2,Plus,CheckCircle2,Download,Upload}from'lucide-react';
type Note={id:number,name:string,phone:string,detail:string,amount:number,status:string};type Invoice={id:number,customer:string,amount:number,status:'Unpaid'|'Paid',date:string};
const money=(n:number)=>new Intl.NumberFormat('ms-MY',{style:'currency',currency:'MYR'}).format(n);
const seedNotes:Note[]=[{id:1,name:'Aisyah',phone:'012-345 6789',detail:'2 × Kek Batik · Jumaat',amount:50,status:'Belum Bayar'},{id:2,name:'Farah',phone:'',detail:'Gift set × 1',amount:35,status:'Selesai'}];
const seedInv:Invoice[]=[{id:1,customer:'Aisyah',amount:50,status:'Paid',date:'27 Sep 2026'},{id:2,customer:'Farah',amount:35,status:'Paid',date:'27 Sep 2026'},{id:3,customer:'Nurul',amount:120,status:'Unpaid',date:'27 Sep 2026'}];
const ms={home:'Utama',notes:'Nota',calc:'Kira',docs:'Dokumen',design:'Reka',welcome:'Urus bisnes lebih mudah.',local:'Rekod anda kekal pada peranti ini.',recent:'Aktiviti terkini'};
const en={home:'Home',notes:'Notes',calc:'Calculate',docs:'Documents',design:'Design',welcome:'Run your business simply.',local:'Your records stay on this device.',recent:'Recent activity'};
export default function App(){const[page,setPage]=useState('home');const[lang,setLang]=useState<'ms'|'en'>('ms');const t=lang==='ms'?ms:en;
const[notes,setNotes]=useState<Note[]>(()=>JSON.parse(localStorage.getItem('satu-notes')||JSON.stringify(seedNotes)));const[invoices,setInvoices]=useState<Invoice[]>(()=>JSON.parse(localStorage.getItem('satu-invoices')||JSON.stringify(seedInv)));
const[cost,setCost]=useState(18),[price,setPrice]=useState(30),[qty,setQty]=useState(2),[extra,setExtra]=useState(0);const calc=useMemo(()=>{const revenue=price*qty,total=cost*qty+extra,profit=revenue-total;return{revenue,total,profit,margin:revenue?profit/revenue*100:0}},[cost,price,qty,extra]);
const persist=(n=notes,i=invoices)=>{localStorage.setItem('satu-notes',JSON.stringify(n));localStorage.setItem('satu-invoices',JSON.stringify(i))};
const addNote=()=>{const n=[{id:Date.now(),name:'Pelanggan baharu',phone:'',detail:'Pesanan baharu',amount:0,status:'Belum Bayar'},...notes];setNotes(n);persist(n,invoices)};
const addInvoice=(customer='Pelanggan',amount=calc.revenue)=>{const i=[...invoices,{id:Math.max(0,...invoices.map(x=>x.id))+1,customer,amount,status:'Unpaid' as const,date:new Date().toLocaleDateString('ms-MY')}];setInvoices(i);persist(notes,i);setPage('docs')};
const markPaid=(id:number)=>{const i=invoices.map(x=>x.id===id?{...x,status:'Paid' as const}:x);setInvoices(i);persist(notes,i)};
const share=async(text:string)=>{try{if(navigator.share)await navigator.share({text});else{await navigator.clipboard.writeText(text);alert('Disalin ke clipboard')}}catch{}};
const backup=()=>{const b=new Blob([JSON.stringify({version:1,notes,invoices,lang},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='SATU-backup.json';a.click();URL.revokeObjectURL(a.href)};
return <div className="app"><header><div><b>SATU</b><small>Nota. Kira. Reka. Semua dalam SATU.</small></div><button className="ghost" onClick={()=>setPage('settings')}><Settings size={20}/></button></header><main>
{page==='home'&&<><section className="hero"><span>SELAMAT DATANG 👋</span><h1>{t.welcome}</h1><p>{t.local}</p></section><h2>Apa nak buat sekarang?</h2><div className="grid">{[['notes','📝','Nota','Pelanggan & pesanan'],['calc','🧮','Kira','Untung & margin'],['docs','🧾','Invoice','Invoice & resit'],['design','🎨','Reka','Template promosi']].map(x=><button className="card action" key={x[0]} onClick={()=>setPage(x[0])}><i>{x[1]}</i><b>{x[2]}</b><small>{x[3]}</small></button>)}</div><h2>{t.recent}</h2><div className="card"><b>INV-{String(invoices.at(-1)?.id||1).padStart(4,'0')} · {invoices.at(-1)?.customer}</b><p>{money(invoices.at(-1)?.amount||0)} · {invoices.at(-1)?.status}</p></div></>}
{page==='notes'&&<><Title title="Nota" sub="Pelanggan, pesanan dan perkara penting."/><button className="primary" onClick={addNote}><Plus size={18}/> Nota baharu</button>{notes.map(n=><div className="card" key={n.id}><b>{n.name}</b><small>{n.phone}</small><p>{n.detail}</p><span className="badge">{n.status}</span><strong>{money(n.amount)}</strong><button className="secondary" onClick={()=>addInvoice(n.name,n.amount)}>Buat Invoice</button></div>)}</>}
{page==='calc'&&<><Title title="Kira" sub="Semak untung sebelum jual."/><Num label="Modal seunit" v={cost} set={setCost}/><Num label="Harga jual seunit" v={price} set={setPrice}/><Num label="Kuantiti" v={qty} set={setQty}/><Num label="Kos tambahan" v={extra} set={setExtra}/><section className="result"><small>RINGKASAN</small><p>Jualan <b>{money(calc.revenue)}</b></p><p>Jumlah kos <b>{money(calc.total)}</b></p><h1>Untung {money(calc.profit)}</h1><p>Margin <b>{calc.margin.toFixed(1)}%</b></p></section><button className="primary" onClick={()=>addInvoice()}>Buat Invoice</button></>}
{page==='docs'&&<><Title title="Invoice" sub="Invoice ringkas untuk pelanggan."/><button className="primary" onClick={()=>addInvoice('Pelanggan baharu',0)}><Plus size={18}/> Invoice baharu</button>{[...invoices].reverse().map(i=><div className="card" key={i.id}><div className="row"><b>INV-{String(i.id).padStart(4,'0')}</b><span className="badge">{i.status}</span></div><h3>{i.customer}</h3><strong>{money(i.amount)}</strong><small>{i.date}</small>{i.status==='Unpaid'?<button className="secondary" onClick={()=>markPaid(i.id)}><CheckCircle2 size={17}/> Tandakan Dibayar</button>:<button className="secondary" onClick={()=>share(`SATU Resit RCP-${String(i.id).padStart(4,'0')} · ${i.customer} · ${money(i.amount)} · Dibayar`)}><Share2 size={17}/> Kongsi Resit</button>}</div>)}</>}
{page==='design'&&<><Title title="Reka" sub="Bahan promosi mudah tanpa AI berbayar."/>{['Produk Promo','Senarai Harga','Pengesahan Pesanan','Peringatan Bayaran','Terima Kasih'].map((x,j)=><div className="card template" key={x}><div className={'preview p'+j}><b>{x}</b><span>SATU</span></div><button className="secondary" onClick={()=>share(x+' — dibuat dengan SATU')}><Share2 size={17}/> Guna template</button></div>)}</>}
{page==='settings'&&<><Title title="Tetapan" sub="Profil, bahasa dan data."/><div className="card"><b>Bahasa aplikasi</b><div className="seg"><button className={lang==='ms'?'on':''} onClick={()=>setLang('ms')}>Bahasa Melayu</button><button className={lang==='en'?'on':''} onClick={()=>setLang('en')}>English</button></div></div><div className="card"><b>Backup & Pulih</b><p>Data SATU V1 disimpan secara lokal pada peranti.</p><button className="secondary" onClick={backup}><Download size={17}/> Export JSON</button><label className="secondary file"><Upload size={17}/> Import JSON<input type="file" accept=".json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{const d=JSON.parse(await f.text());if(d.notes&&d.invoices){setNotes(d.notes);setInvoices(d.invoices);persist(d.notes,d.invoices);alert('Backup dipulihkan')}}catch{alert('Fail backup tidak sah')}}}/></label></div><div className="notice">SATU V1 bukan perisian perakaunan atau invois cukai.</div></>}
</main><nav>{[[Home,'home',t.home],[NotebookPen,'notes',t.notes],[Calculator,'calc',t.calc],[FileText,'docs',t.docs],[Palette,'design',t.design]].map(([Icon,p,l]:any)=><button key={p} className={page===p?'active':''} onClick={()=>setPage(p)}><Icon size={20}/><span>{l}</span></button>)}</nav></div>}
function Title({title,sub}:{title:string,sub:string}){return <div className="title"><h1>{title}</h1><p>{sub}</p></div>}
function Num({label,v,set}:{label:string,v:number,set:(n:number)=>void}){return <label className="field"><small>{label}</small><input type="number" value={v} onChange={e=>set(Number(e.target.value))}/></label>}
